#include "general.h"

/* stmt
 *
 * <stmt> → {id = } <expr> | DUMP | QUIT
 */
void stmt() 
{
   printf("Enter <stmt>\n");
   int left;
   item * var_pos;

   if ( nextToken == DUMP ) {
   	s->dump();
   } else if ( nextToken == QUIT ) {
   	exit(1);
   //if the next token is not dump or quit, you need to check
   //for any of the possible ways an expr can begin
   } else if(nextToken == IDENT){
      var_pos = s->lookup(lexeme);
      lex();
      if(nextToken == ASSIGN_OP){
         lex();
         left = expr();
         var_pos->val = left;
      }
      else if(nextToken == ADD_OP || nextToken == MULT_OP ||
              nextToken == SUB_OP || nextToken == DIV_OP
             || nextToken == EXP_OP){
         cout << "------------ lexeme[0] is " << lexeme[0] << endl;
         ungetc(lexeme[0],stdin);
         cout << "-------------- var length" << var_pos->var.length() << endl;
         for(int i=(var_pos->var).length()-1;i>=0;i--){
            ungetc(var_pos->var[i],stdin);
         }
         getChar();
         lex();
         left=expr();
         char temp[100];
         sprintf(temp,"%d",left);
         if(result[strlen(result)-1] == '=')
            strcat(result,temp);
         else{
            strcat(result,"=");
            strcat(result,temp);
         }
      }
   } else if(nextToken == INT_LIT || nextToken == LEFT_PAREN){
      left = expr();
      char temp[100];
      sprintf(temp,"%d",left);
      if(result[strlen(result)-1] == '=')
         strcat(result,temp);
      else{
         strcat(result,"=");
         strcat(result,temp);
      }
        
   }
   else {
   	error("expected DUMP, QUIT, assignment, or expression");
   }

   printf("Exit <stmt>\n");

   cout << endl;
   cout << "exiting stmt RETURNING " << left << endl;
} /* End of function stmt_list */

/* expr
   Parses strings in the language generated by the rule:
   <expr> -> <term> {(+ | -) <term>}
 */
int expr() 
{
   printf("Enter <expr>\n");

   int right,left,operation;

   /* Parse the first term */
   left = term();
   //left = number;
   cout << " IN EXPR left is = " << left << endl;

   /* As long as the next token is + or -, get
      the next token and parse the next term */
   while (nextToken == ADD_OP || nextToken == SUB_OP) {
      operation = nextToken;
      lex();
      right=term();
      cout << " IN EXPR right is = " << right << endl;
      if(operation == ADD_OP)
         left+=right;
      else if(operation == SUB_OP)
         left-=right;
      else
         error("expected - or +");
   }
   printf("Exit <expr>\n");

   cout << endl;
   cout << "exiting expr RETURNING " << left << endl;
   return left;
} /* End of function expr */


/* term
 *  Parses strings in the language generated by the rule:
 *  <term> -> <sfactor> {(* | /) <sfactor>)
 */
int term() 
{
   printf("Enter <term>\n");
   /* Parse the first factor */
   
   int right,left,operation;

   left=sfactor();
   /* As long as the next token is * or /, get the
      next token and parse the next factor */
   while (nextToken == MULT_OP || nextToken == DIV_OP) {
      operation = nextToken;
      lex();
      right=sfactor();
      if(operation == MULT_OP)
         left*=right;
      else if(operation == DIV_OP)
         left/=right;
      else
         error("expected * or /");
   }
   printf("Exit <term>\n");

   cout << endl;
   cout << "exiting term RETURNING " << left << endl;
   return left;
} /* End of function term */

/* sfactor
 * Parses strings in the language generated by the rule:
 * 
 *   <sfactor> -> - <efactor> | <efactor>
 *
 */
int sfactor() 
{
   printf("Enter <sfactor>\n");
   int val;
   /* Determine which RHS */
   if ( nextToken == SUB_OP ) {
      lex();
      val = efactor();
      val = -1 * val;
   } else {
      val = efactor();
   }
   printf("Exit <sfactor>\n");
   cout << endl;
   cout << "exiting sfactor RETURNING " << val << endl;
   return val;
}/* End of function efactor */

/* efactor
 * Parses strings in the language generated by the rule:
 * 
 *  <efactor> → {<pfactor> ^} <pfactor>
 *
 */
int efactor() 
{
   printf("Enter <efactor>\n");
   int left, right, operation;
   /* Determine which RHS */
   left = pfactor();
   while( nextToken == EXP_OP ) {
      lex();
      right = pfactor();
      left = pow(left,right);
      lex();
   }

   printf("Exit <efactor>\n");
   cout << endl;
   cout << "exiting efactor RETURNING " << left << endl;
   return left;
}/* End of function efactor */

/* pfactor
 * Parses strings in the language generated by the rule:
 * 
 *   <pfactor> -> id | int_constant | ( <expr> )
 *
 */
int pfactor() 
{
   printf("Enter <pfactor>\n");
   int val;
   item * var_pos;

   /* Determine which RHS */
   //if the next token is an ID we need to check to see if
   //the token following that is an assign op
   if (nextToken == IDENT){
      var_pos = s->lookup(lexeme);
      val = var_pos->val;
      lex();
    }
    //if the token following a number is an assignment then
    //we should try to stop execution of the statement.
    //however if the statement is something like a=b+3=10
    //then a=b+3 will still be executed normally.
    else if(nextToken == INT_LIT){
         val = number;
         lex();
         if(nextToken == ASSIGN_OP){
            error("next expecting assign op after int literal");
            while(nextToken != NEWLINE){
               lex();
            }
         }
   }
   /* If the RHS is ( <expr> ), call lex to pass over the left 
      parenthesis, call expr and check for the right parenthesis */
   else if (nextToken == LEFT_PAREN) {
         lex();
         val = expr();
         if (nextToken == RIGHT_PAREN){
            lex();
         }
         else
            error("left without right paren");
   } else {
   /* It was not an id, an integer literal, or a left
       parenthesis */
       error("expected an id, integer, or a left paren");
   } /* End of else */
   printf("Exit <pfactor>\n");
   cout << endl;
   cout << "exiting pfactor RETURNING " << val << endl;
   return val;
}/* End of function pfactor */

void error(const char *message)
{
   printf("Error: %s\n",message);
}
