#!/bin/bash
# Compare.sh
# Name: Matthew Olker and Alec Cohan
# Date: 1-22-2019
# Class: CSC-4510
# Location: molker/csc4510/P1/Script
# This script is used to compare the output generated by the Test.sh and put into
# the OutFiles directory against the correct outputs in the Correct directory
# No parameters necessary


if [ ! -d "../Correct/" ]; then
	echo "Compare.sh: Correct directory doesn't exist or isn't in the right place"
	exit 2
fi
if [ ! -d "../OutFiles/" ]; then
	echo "Compare.sh: OutFiles directory doesn't exist or isn't in the right place"
	exit 2
fi

success=true

for file in `ls ../OutFiles/`
do
	if test -L $file
	then
		echo "Compare.sh: $file is a link"
	elif [[ -d $file ]]; then
		echo "Compare.sh: $file is a directory"
	else
		error="$(diff "../OutFiles/$file" "../Correct/$file")"
		if [ ! -z "$error" ]
		then
			success=false
			echo "Compare.sh: $file Failed"
		fi
	fi
done

if [ "$success" = true ]; then
	echo "Comparing Successful: All output is correct!"
else 
	echo "Comparing Unsuccessful: Some inconsitent output from Corerct."
fi 