#include "general.h"

/* stmt
 *
 * <stmt> → {id = } <expr> | DUMP | QUIT
 */
void stmt() 
{
   int left;
   item * var_pos;

   if ( nextToken == DUMP ) {
   	s->dump();
   } else if ( nextToken == QUIT ) {
   	exit(1);
   //if the next token is not dump or quit, you need to check
   //for any of the possible ways an expr can begin
   } else if(nextToken == IDENT){
      var_pos = s->lookup(lexeme);
      char temp2[100];
      strcpy(temp2,lexeme);
      lex();
      if(nextToken == ASSIGN_OP){
         strcat(result,temp2);
         lex();
         left = expr();
         var_pos->val = left;
         strcat(result,"=");
         sprintf(temp2,"%d",left);
         strcat(result,temp2);
      }else
         error("expected equals after Id");
   } else if(nextToken == IF){
      if(cond()){
         if(nextToken == THEN){
            lex();
            stmt();
            lex();
         }else
            error("expected a then after a cond");
      }else{
         while(nextToken != FI){
            lex();
         }
      }
   } else if(nextToken == WHILE){
      int cond_pos = cur_pos;
      int cond_class = charClass;
      char cond_char = nextChar;
      while(cond()){
         if(nextToken == DO){
            lex();
            stmt();
            cur_pos = cond_pos;
            nextChar = cond_char;
            charClass = cond_class;
         }
      }
      while(nextToken != NEWLINE)
         lex();
   }else {
   	error("expected DUMP, QUIT, assignment, or expression");
   }
} /* End of function stmt_list */

/* This is the function to handle
 * a cond in a if or while statement
 */
bool cond()
{
   lex();
   int left,right;
   left = expr();
   
   switch(nextToken)
   {
      case ASSIGN_OP:
                     lex();
                     if(nextToken == ASSIGN_OP){
                        lex();
                        right = expr();
                        return (left == right);
                     }else 
                        error("expected equals after equals");   
                   break;
      case BANG_OP:
                   lex();
                   if(nextToken == ASSIGN_OP){
                      lex();
                      right = expr();
                      return (left != right);
                   }else
                       error("expected equals after bang");
                   break;
      case LESS_OP:
                   lex();
                   if(nextToken == ASSIGN_OP){
                      lex();
                      right = expr();
                      return (left <= right);
                   }else if(nextToken == INT_LIT || nextToken == IDENT ||
                            nextToken == SUB_OP || nextToken == LEFT_PAREN){
                      right = expr();
                      return (left < right);
                   }else
                      error("expected something different");
                   break;
      case MORE_OP:
                   lex();
                   if(nextToken == ASSIGN_OP){
                      lex();
                      right = expr();
                      return (left >= right);
                   }else if(nextToken == INT_LIT || nextToken == IDENT ||
                            nextToken == SUB_OP || nextToken == LEFT_PAREN){
                      right = expr();
                      return (left > right);
                   }else
                      error("expected something different");
                   break;
       default:
                    error("expected something different");
                    break;
   }
      
}

/* expr
   Parses strings in the language generated by the rule:
   <expr> -> <term> {(+ | -) <term>}
 */
int expr() 
{
   int right,left,operation;

   /* Parse the first term */
   left = term();

   /* As long as the next token is + or -, get
      the next token and parse the next term */
   while (nextToken == ADD_OP || nextToken == SUB_OP) {
      operation = nextToken;
      lex();
      right=term();
      if(operation == ADD_OP)
         left+=right;
      else if(operation == SUB_OP)
         left-=right;
      else
         error("expected - or +");
   }

   return left;
} /* End of function expr */


/* term
 *  Parses strings in the language generated by the rule:
 *  <term> -> <sfactor> {(* | /) <sfactor>)
 */
int term() 
{
   /* Parse the first factor */
   int right,left,operation;

   left=sfactor();
   /* As long as the next token is * or /, get the
      next token and parse the next factor */
   while (nextToken == MULT_OP || nextToken == DIV_OP || nextToken == MOD_OP) {
      operation = nextToken;
      lex();
      right=sfactor();
      if(operation == MULT_OP){
         left*=right;
      }else if(operation == DIV_OP){
         if(right !=0){
            left/=right;
         } else
            error("division by zero");
      }else if(operation == MOD_OP){
         left%=right;
      }
      else
         error("expected * or /");
   }

   return left;
} /* End of function term */

/* sfactor
 * Parses strings in the language generated by the rule:
 * 
 *   <sfactor> -> - <efactor> | <efactor>
 *
 */
int sfactor() 
{
   int val;
   /* Determine which RHS */
   if ( nextToken == SUB_OP ) {
      lex();
      val = efactor();
      val = -1 * val;
   } else {
      val = efactor();
   }
   return val;
}/* End of function efactor */

/* efactor
 * Parses strings in the language generated by the rule:
 * 
 *  <efactor> → {<pfactor> ^} <pfactor>
 *
 */
int efactor() 
{
   int left, right, operation;
   /* Determine which RHS */
   left = pfactor();
   while( nextToken == EXP_OP ) {
      lex();
      right = pfactor();
      left = pow(left,right);
   }

   return left;
}/* End of function efactor */

/* pfactor
 * Parses strings in the language generated by the rule:
 * 
 *   <pfactor> -> id | int_constant | ( <expr> )
 *
 */
int pfactor() 
{
   int val;
   item * var_pos;

   /* Determine which RHS */
   //if the next token is an ID we need to check to see if
   //the token following that is an assign op
   if (nextToken == IDENT){
      var_pos = s->lookup(lexeme);
      val = var_pos->val;
      lex();
    }
    //if the token following a number is an assignment then
    //we should try to stop execution of the statement.
    //however if the statement is something like a=b+3=10
    //then a=b+3 will still be executed normally.
    else if(nextToken == INT_LIT){
         val = number;
         lex();
         if(nextToken == ASSIGN_OP){
            error("next expecting assign op after int literal");
            while(nextToken != NEWLINE){
               lex();
            }
         }
   }
   /* If the RHS is ( <expr> ), call lex to pass over the left 
      parenthesis, call expr and check for the right parenthesis */
   else if (nextToken == LEFT_PAREN) {
         lex();
         val = expr();
         if (nextToken == RIGHT_PAREN){
            lex();
         }
         else
            error("left without right paren");
   } else {
   /* It was not an id, an integer literal, or a left
       parenthesis */
       error("expected an id, integer, or a left paren");
   } /* End of else */

   return val;
}/* End of function pfactor */

void error(const char *message)
{
   printf("Error: %s\n",message);
}
